# Generated by Django 4.2.9 on 2024-02-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_portal', '0002_subscribes_category_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='staff_pos',
            field=models.CharField(choices=[('AD', 'Администратор'), ('MO', 'Модератор'), ('US', 'Пользователь')], default='US', max_length=2),
        ),
    ]
